const { Router } = require('express')
const router = Router()
const { renderIndex, renderBandeja, renderAsignacion, renderUsuario, renderHorario, renderEquipo, renderRol, renderGrupoGics, renderUsuarioGrupoGics, renderEquipoAsignado, renderZonalAsignado, renderTecnico, renderAsesor, renderEscalamiento, renderReporte } = require('../controllers/index')
const {isAuthenticated} = require('../helpers/auth')

router.get('/', isAuthenticated, renderIndex)
router.get('/', renderBandeja)
router.get('/', renderAsignacion)
router.get('/', renderUsuario)
router.get('/', renderHorario)
router.get('/', renderReporte)
router.get('/', renderEquipo)
router.get('/', renderRol)
router.get('/', renderEquipoAsignado)
router.get('/', renderZonalAsignado)
router.get('/', renderGrupoGics)
router.get('/', renderUsuarioGrupoGics)
router.get('/', renderTecnico)
router.get('/', renderEscalamiento)
router.get('/', renderAsesor)

module.exports = router